name: Build and Deploy (TESTING)

# All commented-out lines will need to be un-commented before merging. These are currently commented
# out for debugging and testing during the actual PR, which, obviously, involves changes to this
# workflow itself.

on:
  # push:
  #   branches:
  #     - main
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create and activate conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: website-redesign
          environment-file: environment.yml

      - name: Build Website
        run: python build.py

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .
