name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create and activate conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: website-redesign
          environment-file: environment.yml

      - name: Modify .gitignore
        run: |
          # Remove the line that ignores HTML files in the content directory
          sed -i '/content\/\*\*\/\.html/d' .gitignore
          cat .gitignore

      - name: Build Website
        run: python build.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
