name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create and activate conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: website-redesign
          environment-file: environment.yml

      - name: Build Website
        run: python build.py

      - name: Add generated HTML files to git
        run: |
          git add content/**/*.html
          git commit -m "Add generated HTML files" || echo "No changes to commit"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
