name: Build and Deploy Dev website using HNN master

on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false

      - name: Create Conda Environment With MPI and Master HNN version
        run: make create-textbook-dev-build

      - name: Test MPI
        run: |
          conda run -n textbook-dev-build \
          mpiexec -np 2 nrniv -mpi -python -c '
          from neuron import h;
          from mpi4py import MPI;
          print(f"Hello from proc {MPI.COMM_WORLD.Get_rank()}");
          h.quit()'

      - name: Build Website
        run: |
          conda run -n textbook-dev-build env PYTHONUNBUFFERED=1 \
          python build.py \
          --code-version master \
          --execution-type execute-updated-unskipped-notebooks

      - name: Deploy to GitHub Pages (Fork)
        if: github.repository != 'jonescompneurolab/textbook'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
