name: Test, Build, and Deploy PR Stable / Dev Websites

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-build-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for dev/ in .gitignore
        run: |
          if ! grep -qx 'dev/' .gitignore; then
            echo "dev/ not found in .gitignore, exiting."
            exit 1
          fi

      - name: Modify .gitignore
        run: |
          # Remove the lines that ignore HTML and dev/ files in the content directory
          grep -v '^content/\*\*/\*.html$' .gitignore > .gitignore.tmp && mv .gitignore.tmp .gitignore
          grep -v '^dev\/$' .gitignore > .gitignore.tmp && mv .gitignore.tmp .gitignore
          cat .gitignore

      - name: Set Up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false

      - name: Create Conda Environment With MPI and Stable HNN version
        run: make create-textbook-stable-env

      - name: Test MPI (Stable)
        run: |
          conda run -n textbook-stable-env \
          mpiexec -np 2 nrniv -mpi -python -c '
          from neuron import h;
          from mpi4py import MPI;
          print(f"Hello from proc {MPI.COMM_WORLD.Get_rank()}");
          h.quit()'

      - name: Determine Build Method (Stable)
        run: |
          if conda run -n textbook-stable-env python scripts/check_nb_versions.py; then
            echo "BUILD_FLAG=--execution-type updated-unskipped-notebooks" >> $GITHUB_ENV
          else
            echo "BUILD_FLAG=--execution-type all-unskipped-notebooks" >> $GITHUB_ENV
            echo "Not all notebooks were executed on the latest version. Forcing re-execution."
          fi

      - name: Build Website (Stable)
        continue-on-error: true
        run: |
          conda run -n textbook-stable-env env \
              PYTHONUNBUFFERED=1 python build.py \
              $BUILD_FLAG

      - name: Create Conda Environment With MPI and Dev (Master) HNN version
        run: make create-textbook-dev-env

      - name: Test MPI (Master)
        run: |
          conda run -n textbook-dev-env \
          mpiexec -np 2 nrniv -mpi -python -c '
          from neuron import h;
          from mpi4py import MPI;
          print(f"Hello from proc {MPI.COMM_WORLD.Get_rank()}");
          h.quit()'

      - name: Build Website (Master, Dev)
        continue-on-error: true
        run: |
            # Should NOT re-use BUILD_FLAG for master build
            conda run -n textbook-dev-env env \
                PYTHONUNBUFFERED=1 python build.py \
                --execution-type updated-unskipped-notebooks --code-version=master

      - name: Deploy to GitHub Pages (Fork)
        if: github.repository != 'jonescompneurolab/textbook'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: ${{ github.head_ref }}
